export { quartoReducer } from './quartoSlice';

export {
  startLocalGame,
  startAIGame,
  setOnlineGame,
  resetGame,
  selectPiece,
  placePiece,
  callQuarto,
  setAIThinking,
  applyAIMove,
  setConnectionStatus,
  handlePlayerLeft,
  setSelectedPosition,
  setHoveredPosition,
  setError,
} from './quartoSlice';

export {
  selectQuartoState,
  selectGame,
  selectUI,
  selectBoard,
  selectCurrentPlayer,
  selectOpponentPlayer,
  selectIsMyTurn,
  selectAvailablePieces,
  selectSelectedPiece,
  selectCanCallQuarto,
  selectWinningLines,
  selectGameStatus,
  selectGamePhase,
  selectWinner,
  selectWinnerPlayer,
  selectIsGameOver,
  selectIsPlaying,
  selectIsWaiting,
  selectGameMode,
  selectMoveHistory,
  selectMoveCount,
  selectPlacedPiecesCount,
  selectEmptyPositions,
  selectSelectedPosition,
  selectHoveredPosition,
  selectIsAIThinking,
  selectConnectionStatus,
  selectError,
  selectIsConnected,
  selectIsConnecting,
} from './selectors';
