/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesQuartoIndexRouteImport } from './routes/games/quarto/index'
import { Route as GamesQuartoRulesRouteImport } from './routes/games/quarto/rules'
import { Route as GamesQuartoPlayRouteImport } from './routes/games/quarto/play'
import { Route as GamesQuartoOnlineRouteImport } from './routes/games/quarto/online'
import { Route as GamesQuartoJoinRouteImport } from './routes/games/quarto/join'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesQuartoIndexRoute = GamesQuartoIndexRouteImport.update({
  id: '/games/quarto/',
  path: '/games/quarto/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesQuartoRulesRoute = GamesQuartoRulesRouteImport.update({
  id: '/games/quarto/rules',
  path: '/games/quarto/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesQuartoPlayRoute = GamesQuartoPlayRouteImport.update({
  id: '/games/quarto/play',
  path: '/games/quarto/play',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesQuartoOnlineRoute = GamesQuartoOnlineRouteImport.update({
  id: '/games/quarto/online',
  path: '/games/quarto/online',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesQuartoJoinRoute = GamesQuartoJoinRouteImport.update({
  id: '/games/quarto/join',
  path: '/games/quarto/join',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games/quarto/join': typeof GamesQuartoJoinRoute
  '/games/quarto/online': typeof GamesQuartoOnlineRoute
  '/games/quarto/play': typeof GamesQuartoPlayRoute
  '/games/quarto/rules': typeof GamesQuartoRulesRoute
  '/games/quarto': typeof GamesQuartoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/quarto/join': typeof GamesQuartoJoinRoute
  '/games/quarto/online': typeof GamesQuartoOnlineRoute
  '/games/quarto/play': typeof GamesQuartoPlayRoute
  '/games/quarto/rules': typeof GamesQuartoRulesRoute
  '/games/quarto': typeof GamesQuartoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games/quarto/join': typeof GamesQuartoJoinRoute
  '/games/quarto/online': typeof GamesQuartoOnlineRoute
  '/games/quarto/play': typeof GamesQuartoPlayRoute
  '/games/quarto/rules': typeof GamesQuartoRulesRoute
  '/games/quarto/': typeof GamesQuartoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/games/quarto/join'
    | '/games/quarto/online'
    | '/games/quarto/play'
    | '/games/quarto/rules'
    | '/games/quarto'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/games/quarto/join'
    | '/games/quarto/online'
    | '/games/quarto/play'
    | '/games/quarto/rules'
    | '/games/quarto'
  id:
    | '__root__'
    | '/'
    | '/games/quarto/join'
    | '/games/quarto/online'
    | '/games/quarto/play'
    | '/games/quarto/rules'
    | '/games/quarto/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesQuartoJoinRoute: typeof GamesQuartoJoinRoute
  GamesQuartoOnlineRoute: typeof GamesQuartoOnlineRoute
  GamesQuartoPlayRoute: typeof GamesQuartoPlayRoute
  GamesQuartoRulesRoute: typeof GamesQuartoRulesRoute
  GamesQuartoIndexRoute: typeof GamesQuartoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/quarto/': {
      id: '/games/quarto/'
      path: '/games/quarto'
      fullPath: '/games/quarto'
      preLoaderRoute: typeof GamesQuartoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/quarto/rules': {
      id: '/games/quarto/rules'
      path: '/games/quarto/rules'
      fullPath: '/games/quarto/rules'
      preLoaderRoute: typeof GamesQuartoRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/quarto/play': {
      id: '/games/quarto/play'
      path: '/games/quarto/play'
      fullPath: '/games/quarto/play'
      preLoaderRoute: typeof GamesQuartoPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/quarto/online': {
      id: '/games/quarto/online'
      path: '/games/quarto/online'
      fullPath: '/games/quarto/online'
      preLoaderRoute: typeof GamesQuartoOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/quarto/join': {
      id: '/games/quarto/join'
      path: '/games/quarto/join'
      fullPath: '/games/quarto/join'
      preLoaderRoute: typeof GamesQuartoJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesQuartoJoinRoute: GamesQuartoJoinRoute,
  GamesQuartoOnlineRoute: GamesQuartoOnlineRoute,
  GamesQuartoPlayRoute: GamesQuartoPlayRoute,
  GamesQuartoRulesRoute: GamesQuartoRulesRoute,
  GamesQuartoIndexRoute: GamesQuartoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
