/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesQuartoIndexRouteImport } from './routes/games/quarto/index'
import { Route as GamesQuartoPlayRouteImport } from './routes/games/quarto/play'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesQuartoIndexRoute = GamesQuartoIndexRouteImport.update({
  id: '/games/quarto/',
  path: '/games/quarto/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesQuartoPlayRoute = GamesQuartoPlayRouteImport.update({
  id: '/games/quarto/play',
  path: '/games/quarto/play',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games/quarto/play': typeof GamesQuartoPlayRoute
  '/games/quarto': typeof GamesQuartoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/quarto/play': typeof GamesQuartoPlayRoute
  '/games/quarto': typeof GamesQuartoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games/quarto/play': typeof GamesQuartoPlayRoute
  '/games/quarto/': typeof GamesQuartoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/games/quarto/play' | '/games/quarto'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/games/quarto/play' | '/games/quarto'
  id: '__root__' | '/' | '/games/quarto/play' | '/games/quarto/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesQuartoPlayRoute: typeof GamesQuartoPlayRoute
  GamesQuartoIndexRoute: typeof GamesQuartoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/quarto/': {
      id: '/games/quarto/'
      path: '/games/quarto'
      fullPath: '/games/quarto'
      preLoaderRoute: typeof GamesQuartoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/quarto/play': {
      id: '/games/quarto/play'
      path: '/games/quarto/play'
      fullPath: '/games/quarto/play'
      preLoaderRoute: typeof GamesQuartoPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesQuartoPlayRoute: GamesQuartoPlayRoute,
  GamesQuartoIndexRoute: GamesQuartoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
